export const items = [
  { name: 'Robert Downey Jr.', age: 56, birth: 'USA',	netWorthMillions: 300,	married: 2,	children: 3 },
  { name: 'Tom Cruise', age: 59, birth: 'USA',	netWorthMillions: 600,	married: 3,	children: 3 },
  { name: 'Kim Kardashian', age: 40, birth: 'USA', netWorthMillions: 1200,	married: 3,	children: 4 },
  { name: 'Jennifer Aniston', age: 52, birth: 'USA',	netWorthMillions: 300,	married: 2,	children: 0 },
  { name: 'Tom Hanks', age: 65, birth: 'USA',	netWorthMillions: 400,	married: 2,	children: 4 },
  { name: 'Cardi B', age: 28, birth: 'USA',	netWorthMillions: 24,	married: 1,	children: 2 },
  { name: 'Matt Damon', age: 50, birth: 'USA',	netWorthMillions: 170,	married: 1,	children: 3 },
  { name: 'Jennifer Lawrence', age: 31, birth: 'USA',	netWorthMillions: 160,	married: 1,	children: 0 },
  { name: 'Nicholas Cage', age: 57, birth: 'USA',	netWorthMillions: 25,	married: 5,	children: 2 },
  { name: 'Scarlett Johansson', age: 36, birth: 'USA',	netWorthMillions: 165,	married: 3,	children: 2 },
  { name: 'Keanu Reeves', age: 57, birth: 'Lebanon',	netWorthMillions: 350,	married: 0,	children: 0 },
  { name: 'Will Smith', age: 52, birth: 'USA',	netWorthMillions: 350,	married: 2,	children: 3 },
  { name: 'Natalie Portman', age: 40, birth: 'Israel',	netWorthMillions: 90,	married: 1,	children: 2 },
  { name: 'Charlize Theron', age: 46, birth: 'South Africa',	netWorthMillions: 160,	married: 0,	children: 2 },
  { name: 'Daniel Radcliffe', age: 32, birth: 'UK',	netWorthMillions: 110,	married: 0,	children: 0 },
  { name: 'Brad Pitt', age: 57, birth: 'USA',	netWorthMillions: 300,	married: 2,	children: 6 },
  { name: 'Ryan Reynolds', age: 44, birth: 'Canada',	netWorthMillions: 150,	married: 2,	children: 3 },
  { name: 'Seth Rogen', age: 39, birth: 'Canada',	netWorthMillions: 80,	married: 1,	children: 0 },
  { name: 'Michael J. Fox', age: 60, birth: 'Canada',	netWorthMillions: 65,	married: 1,	children: 4 },
  { name: 'Jude Law', age: 48, birth: 'UK',	netWorthMillions: 65,	married: 2,	children: 6 },
  { name: 'Kate Winslet', age: 45, birth: 'UK',	netWorthMillions: 65,	married: 3,	children: 3 },
  { name: 'Robert Pattinson', age: 35, birth: 'UK',	netWorthMillions: 100,	married: 0,	children: 0 },
  { name: 'Jim Carrey', age: 58, birth: 'Canada',	netWorthMillions: 180,	married: 2,	children: 1 },
  { name: 'Hugh Jackman', age: 52, birth: 'Australia',	netWorthMillions: 180,	married: 1,	children: 2 }
]
