export const items = [
  { name: 'Avengers End Game', releaseYear: 2019, boxOfficeMillions: 2800, budgetMillions: 400, femaleDirector: false, duration: 181, rating: 'PG-13' },
  { name: 'Terminator', releaseYear: 1984, boxOfficeMillions: 78.3, budgetMillions: 6.4, femaleDirector: false, duration: 107, rating: 'R' },
  { name: 'Jurassic Park', releaseYear: 1993, boxOfficeMillions: 1300, budgetMillions: 63, femaleDirector: false, duration: 128, rating: 'PG-13' },
  { name: 'Mean Girls', releaseYear: 2004, boxOfficeMillions: 130.1, budgetMillions: 17, femaleDirector: false, duration: 97, rating: 'PG-13' },
  { name: 'Toy Story 2', releaseYear: 1999, boxOfficeMillions: 497.4, budgetMillions: 90, femaleDirector: false, duration: 92, rating: 'G' },
  { name: 'Titanic', releaseYear: 1997, boxOfficeMillions: 2200, budgetMillions: 200, femaleDirector: false, duration: 195, rating: 'PG-13' },
  { name: 'Lord of the Rings: Fellowship of the Ring', releaseYear: 2001, boxOfficeMillions: 897.7, budgetMillions: 93, femaleDirector: false, duration: 178, rating: 'PG-13' },
  { name: 'Brokeback Mountain', releaseYear: 2005, boxOfficeMillions: 178.1, budgetMillions: 14, femaleDirector: false, duration: 134, rating: 'R' },
  { name: 'Inception', releaseYear: 2010, boxOfficeMillions: 836.8, budgetMillions: 160, femaleDirector: false, duration: 148, rating: 'PG-13' },
  { name: 'Clueless', releaseYear: 1995, boxOfficeMillions: 56.6, budgetMillions: 12, femaleDirector: true, duration: 97, rating: 'PG-13' },
  { name: 'Wonder Woman', releaseYear: 2017, boxOfficeMillions: 822.3, budgetMillions: 150, femaleDirector: true, duration: 141, rating: 'PG-13' },
  { name: 'A League of Their Own', releaseYear: 1992, boxOfficeMillions: 132.4, budgetMillions: 40, femaleDirector: true, duration: 128, rating: 'PG' },
  { name: 'Pitch Perfect', releaseYear: 2012, boxOfficeMillions: 115.4, budgetMillions: 17, femaleDirector: false, duration: 112, rating: 'PG-13' },
  { name: 'Twilight', releaseYear: 2008, boxOfficeMillions: 407.1, budgetMillions: 37, femaleDirector: true, duration: 121, rating: 'PG-13' },
  { name: 'Shrek', releaseYear: 2001, boxOfficeMillions: 487.9, budgetMillions: 60, femaleDirector: true, duration: 90, rating: 'PG' },
  { name: 'Frozen', releaseYear: 2013, boxOfficeMillions: 1280, budgetMillions: 150, femaleDirector: true, duration: 102, rating: 'PG' },
  { name: '10 Things I Hate About You', releaseYear: 1999, boxOfficeMillions: 60.4, budgetMillions: 30, femaleDirector: false, duration: 97, rating: 'PG-13' },
  { name: 'Independence Day', releaseYear: 1996, boxOfficeMillions: 817.4, budgetMillions: 75, femaleDirector: false, duration: 145, rating: 'PG-13' },
  { name: 'Finding Nemo', releaseYear: 2003, boxOfficeMillions: 940.3, budgetMillions: 94, femaleDirector: false, duration: 100, rating: 'G' },
  { name: 'Harry Potter: Goblet of Fire', releaseYear: 2005, boxOfficeMillions: 896.5, budgetMillions: 150, femaleDirector: false, duration: 157, rating: 'PG-13' },
]
